0x05-python-exceptions_task
